### ISSUE TITLE
Out of memory, but CUDA only used half of available memory on card

### ISSUE THREAD

**Issue by hhvu0102** [Tuteja-Lab/UnsupervisedPeakCaller#7]
Got error with out of memory (OOM), something like `torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 44.35 GiB total capacity; 43.90 GiB already allocated; 256.00 KiB free; 43.96 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`, with `torch==1.13.1`.

**Comment by hhvu0102** [comment]
Solved by downgrading `torch` to `1.10.0`, see thread https://github.com/pytorch/pytorch/issues/35901 and https://github.com/pytorch/pytorch/pull/44742

**Comment by nchzzDFTBA** [comment]
hi , I wonder how did you resolve the problem, Would you please give me more information? Thank you!

**Comment by hhvu0102** [comment]
Hello,

First, I suggest you try reducing the batch size. If that does not work, you can first uninstall `torch` using the following commands:
```
conda uninstall pytorch -y
yes | pip uninstall torch
```
I recommend you read the uninstallation instruction in this page: https://github.com/pytorch/pytorch/blob/main/CONTRIBUTING.md
Next, you can install `torch` with a specific version requirements, following this page https://pytorch.org/get-started/previous-versions/#v1100
Please let me know if I can help with anything else.
